-- CATEGORY TABLE

 INSERT INTO category(ID,DELETED,CREATED_DATE,UPDATED_DATE,CODE,DESCRIPTION,DISPLAY_NAME,IMAGE_URL) VALUES (1,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'FMCG','Fast-moving consumer goods','FMCG','/fmcg/fmgc.jpg');
 
 INSERT INTO category(ID,DELETED,CREATED_DATE,UPDATED_DATE,CODE,DESCRIPTION,DISPLAY_NAME,IMAGE_URL) VALUES (2,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'STAT','Stationery Items','STAT','/stat/stationery.jpg');
 
 INSERT INTO category(ID,DELETED,CREATED_DATE,UPDATED_DATE,CODE,DESCRIPTION,DISPLAY_NAME,IMAGE_URL) VALUES (3,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'CERL','Cereals foods','CERL','/cerl/cerl.jpg');
 
 INSERT INTO category(ID,DELETED,CREATED_DATE,UPDATED_DATE,CODE,DESCRIPTION,DISPLAY_NAME,IMAGE_URL) VALUES (4,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'PETC','Pet Care food','PETC','/petc/petCare.jpg');

-- ITEM TABLE

 INSERT INTO item(ID,DELETED,CREATED_DATE,UPDATED_DATE,category_CODE,CODE,discountCode,ITEM_UNIT_COUNT,MINIIMAGEURL ,NAME,PRICE,unitTypeCode) VALUES (1,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'FMCG','SOFD','12PERCENT',10,'/fmcg/softDrinks.jpg','Soft Drinks',70,1);
 
  INSERT INTO item(ID,DELETED,CREATED_DATE,UPDATED_DATE,CATEGORY_CODE,CODE,discountCode,ITEM_UNIT_COUNT,MINIIMAGEURL ,NAME,PRICE,unitTypeCode) VALUES (2,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'FMCG','MILK','12PERCENT',10,'/fmcg/milk.jpg','milk',87,1);
   
  INSERT INTO item(ID,DELETED,CREATED_DATE,UPDATED_DATE,CATEGORY_CODE,CODE,discountCode,ITEM_UNIT_COUNT,MINIIMAGEURL ,NAME,PRICE,unitTypeCode) VALUES (3,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'FMCG','CURD','12PERCENT',10,'/fmcg/curd.jpg','curd',22,1);
	
  INSERT INTO item(ID,DELETED,CREATED_DATE,UPDATED_DATE,CATEGORY_CODE,CODE,discountCode,ITEM_UNIT_COUNT,MINIIMAGEURL ,NAME,PRICE,unitTypeCode) VALUES (4,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'FMCG','CHCL','12PERCENT',10,'/fmcg/choclates.jpg','choclates',30,1);
  
  INSERT INTO ITEM(ID,DELETED,CREATED_DATE,UPDATED_DATE,CATEGORY_CODE,CODE,discountCode,ITEM_UNIT_COUNT,MINIIMAGEURL ,NAME,PRICE,unitTypeCode) VALUES (5,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'STAT','PNCL','12PERCENT',10,'/stat/pencil.png','pencil',30,1);
  
  INSERT INTO item(ID,DELETED,CREATED_DATE,UPDATED_DATE,CATEGORY_CODE,CODE,discountCode,ITEM_UNIT_COUNT,MINIIMAGEURL ,NAME,PRICE,unitTypeCode) VALUES (6,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'STAT','PEN','12PERCENT',10,'/stat/pen.png','pen',30,1);
  
  INSERT INTO item(ID,DELETED,CREATED_DATE,UPDATED_DATE,CATEGORY_CODE,CODE,discountCode,ITEM_UNIT_COUNT,MINIIMAGEURL ,NAME,PRICE,unitTypeCode) VALUES (7,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'STAT','ERAS','12PERCENT',10,'/stat/erasure.jpg','erasure',30,1);
  
  
  INSERT INTO item(ID,DELETED,CREATED_DATE,UPDATED_DATE,CATEGORY_CODE,CODE,discountCode,ITEM_UNIT_COUNT,MINIIMAGEURL ,NAME,PRICE,unitTypeCode) VALUES (8,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'CERL','RICE','12PERCENT',10,'/cerl/rice.jpg','rice',30,1);
 
  INSERT INTO item(ID,DELETED,CREATED_DATE,UPDATED_DATE,CATEGORY_CODE,CODE,discountCode,ITEM_UNIT_COUNT,MINIIMAGEURL ,NAME,PRICE,unitTypeCode) VALUES (9,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'CERL','WHET','12PERCENT',10,'/cerl/wheat.jpg','wheat',30,1);
  
   INSERT INTO item(ID,DELETED,CREATED_DATE,UPDATED_DATE,CATEGORY_CODE,CODE,discountCode,ITEM_UNIT_COUNT,MINIIMAGEURL ,NAME,PRICE,unitTypeCode) VALUES (10,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'PETC','SYBN','12PERCENT',10,'/petc/soyabean.jpg','soyabean',30,1);
   
   -- OFFER
   INSERT INTO offer(ID,DELETED,CREATED_DATE,UPDATED_DATE,CODE,DESCRIPTION,END_DATE,IS_ACTIVE,OFFER_TYPE,START_DATE,offer_discount) VALUES (1,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'12PERCENT','12% offer',NULL,1,'PROMOTIONAL',CURRENT_DATE,12);
   
   -- UNIT
   INSERT INTO unit_type(ID,DELETED) VALUES(1,0);